# Generated by Django 4.1.6 on 2023-03-31 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_blogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant_products',
            name='img_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
