# Generated by Django 4.1.6 on 2023-03-31 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_plant_products_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant_products',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
