# Generated by Django 4.1.6 on 2023-03-31 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_plant_products_productdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant_products',
            name='categeory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
