# Generated by Django 4.1.6 on 2023-04-09 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_plant_products_categeory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='product_img2',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='product_img3',
        ),
        migrations.AddField(
            model_name='blogs',
            name='img_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='img_url2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='img_url3',
            field=models.URLField(blank=True, null=True),
        ),
    ]
