# Generated by Django 4.1.6 on 2023-04-09 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_blogs_product_img2_remove_blogs_product_img3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
