# Generated by Django 4.1.6 on 2023-04-10 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_blogs_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seed_products',
            name='product_img',
        ),
        migrations.AddField(
            model_name='seed_products',
            name='img_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
