# Generated by Django 4.1.6 on 2023-04-10 04:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_seed_products_product_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seed_products',
            name='ProductDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='seed_products',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
