# Generated by Django 4.1.6 on 2023-04-10 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_seed_products_productdate_seed_products_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seed_products',
            old_name='ProductDate',
            new_name='product_date',
        ),
    ]
