# Generated by Django 4.1.6 on 2023-04-10 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_productdate_seed_products_product_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seed_products',
            name='img_url',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
