# Generated by Django 4.1.6 on 2023-04-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_seed_products_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seed_products',
            name='img_url',
            field=models.URLField(blank=True, max_length=800, null=True),
        ),
    ]
