# Generated by Django 4.1.6 on 2023-04-10 13:22

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_seed_products_img_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('mobileno1', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('mobileno2', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('Address1', models.TextField()),
                ('Address2', models.TextField()),
                ('pincode', models.CharField(max_length=20)),
                ('cart', models.JSONField()),
            ],
        ),
    ]
