# Generated by Django 4.1.6 on 2023-04-11 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_checkoutinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant_products',
            name='product_img',
        ),
    ]
