# Generated by Django 4.1.6 on 2023-04-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_plant_products_product_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_db',
            name='country',
        ),
        migrations.RemoveField(
            model_name='contact_db',
            name='sex',
        ),
        migrations.AddField(
            model_name='contact_db',
            name='city',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='contact_db',
            name='state',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
